#!/bin/bash -eux
source "$(dirname $0)/bin/conf"

[ "$USER" = "root" ]

### CREATE DIRECTORIES ###
mkdir -p "$logdir" "$datadir" "$datadir/counters"
chown www-data:www-data "$logdir" "$datadir" "$datadir/counters" -R
chmod 777 "$logdir" "$datadir" "$datadir/counters"

### INSTALLTHISSYSTEM ###
rsync -av --delete "$(dirname $0)/bin/" "$appdir/"
chown www-data:www-data "$appdir"

### RENAME FETCH CGI ###
cd "$appdir"
rnd=$(cat /dev/urandom | tr -cd 0-9a-zA-Z | head -c 32)
mv "fetch" "fetch_$rnd.cgi"

### PULL ARTICLE REPO ###
rm -rf "{$contentsdir:?}"
cd "$wwwdir"
git clone "https://github.com/$contents_owner/$contents"
chown www-data:www-data "$contentsdir" -R

echo "call fetch_$rnd.cgi from GitHub"
